FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY MockIngressAgent/*.csproj ./MockIngressAgent/
COPY ConfigRemote/*.csproj ./ConfigRemote/
RUN dotnet restore MockIngressAgent

# copy everything else and build app
COPY MockIngressAgent/. ./MockIngressAgent/
COPY ConfigRemote/. ./ConfigRemote/
WORKDIR /app/MockIngressAgent
RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/core/runtime:3.1 AS runtime
WORKDIR /app
COPY --from=build /app/MockIngressAgent/out ./
ENTRYPOINT ["dotnet", "MockIngressAgent.dll"]
