FROM mcr.microsoft.com/dotnet/core/sdk:3.1
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY MockWebApi/*.csproj ./MockWebApi/
RUN dotnet restore MockWebApi

# copy everything else and build app
COPY MockWebApi/. ./MockWebApi/

WORKDIR /app/MockWebApi
ENTRYPOINT ["dotnet", "run", "--launch-profile", "MockWebApi", "-c", "Release", "MockWebApi.dll"]
