FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY IngressAgent/*.csproj ./IngressAgent/
RUN dotnet restore IngressAgent

# copy everything else and build app
COPY IngressAgent/. ./IngressAgent/
WORKDIR /app/IngressAgent
RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/core/runtime:3.1 AS runtime
WORKDIR /app
COPY --from=build /app/IngressAgent/out ./
ENTRYPOINT ["dotnet", "IngressAgent.dll"]
