FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY LoadBalancer/*.csproj ./LoadBalancer/
RUN dotnet restore LoadBalancer

# copy everything else and build app
COPY LoadBalancer/. ./LoadBalancer/
WORKDIR /app/LoadBalancer
RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
WORKDIR /app
COPY --from=build /app/LoadBalancer/out ./
ENTRYPOINT ["dotnet", "LoadBalancer.dll"]
